server:  
  port: 8888

eureka:
  instance:
    # host名称,单机版需要修改host 127.0.0.1  registry
    hostname: registry
    # 将IP注册到Eureka Server上
    prefer-ip-address: true
    metadata-map:
      # 设置用户名密码
      user.name: ${security.user.name}
      user.password: ${security.user.password}
  client:
    # Eureka服务的地址(注意:地址最后面的/eureka/是固定值)
    service-url:
      defaultZone: http://user:${REGISTRY_SERVER_PASSWORD:password}@registry:8761/eureka/

spring:
  cloud:  
    config:  
      enabled: true  
      server:  
        svn:  
          uri: svn://39.108.57.32/code/cloud-config/  
          username: liukl  
          password: liukl  
        #git:  
        #uri: https://github.com/pcf-guides/configuration-server-config-repo
        #可以指定默认文件配置目录,不指定默认trunk下面
        #default-label: config  
  profiles:  
    active: subversion
  rabbitmq:
      host: 39.108.57.32
      username: admin
      password: admin
      port: 5672

security:
  user:
    name: user
    password: ${CONFIG_SERVER_PASSWORD:password}
