spring:
  application:
    name: zipkin
  rabbitmq:
    host: 39.108.57.32
    username: admin
    password: admin
    port: 5672

server:
  port: 9411

security:
  user:
    name: admin
    password: ${ZIPKIN_SERVER_PASSWORD:admin}